# Generated by Django 5.2.17 on 2026-09-19 19:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('E', 'Egresado')], default='A', max_length=1)),
                ('semestre', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código identificador de la carrera', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Ej. Ingeniería en Sistemas Computacionales', max_length=40)),
                ('creditos', models.PositiveIntegerField(help_text='Total de créditos de la carrera')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en semestres')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alumnos', to='catalog.carrera'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('cupo', models.PositiveIntegerField()),
                ('numAlumnos', models.PositiveIntegerField(default=0, help_text='Cantidad actual de alumnos inscritos')),
                ('horario', models.CharField(max_length=100)),
                ('alumnos', models.ManyToManyField(help_text='Alumnos inscritos en este grupo', through='catalog.Calificacion', to='catalog.alumno')),
            ],
            options={
                'ordering': ['materia', 'clave'],
            },
        ),
        migrations.AddField(
            model_name='calificacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.grupo'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('unidades', models.PositiveIntegerField(help_text='Número de unidades del temario')),
                ('creditos', models.PositiveIntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='catalog.carrera')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='catalog.materia'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('alumno', 'grupo'), name='unique_alumno_grupo'),
        ),
    ]
