# Generated by Django 5.2.17 on 2026-09-22 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('numero_empleado', models.CharField(help_text='Número de nómina o identificador del docente', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Correo institucional', max_length=254, unique=True)),
                ('especialidad', models.CharField(blank=True, help_text='Ej. Ingeniería en Sistemas Computacionales, Ciencias Básicas', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='catalog.profesor'),
        ),
    ]
